<div>
    The following error occurred while capturing TF Repayment for {{$data['cust_id']}} and for the FA {{$data['loan_doc_id']}} at {{$data['failed_at']}}.<br/>
    <p><pre style="color:maroon">{{$data['exception']}}</pre></p> <br>
</div>